NAME = libftprintf.a
CC = gcc
CFLAGS = -Wall -Wextra -Werror
AR = ar rcs

LIBFT = libft/libft.a
LIBFT_DIR =libft

SRC = src/ft_printf.c src/print_char.c src/print_hex.c src/print_number.c src/print_pointer.c src/print_string.c src/print_unsigned.c
OBJ = $(SRC:.c=.o)

INCLUDES = -I libft

all: $(NAME)

$(NAME): $(LIBFT) $(OBJ)
	$(AR) $(NAME) $(OBJ) $(LIBFT_DIR)/*.o

$(LIBFT):
	$(MAKE) -C $(LIBFT_DIR)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@ $(INCLUDES)

clean:
	$(RM) $(OBJ)
	$(MAKE) -C $(LIBFT_DIR) clean

fclean: clean
	$(RM) $(NAME)
	$(MAKE) -C $(LIBFT_DIR) fclean

re: fclean all

.PHONY: all clean fclean re